name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p upload
      - run: echo "Hello, world!" > upload/test.txt
      - run: ls -al
      - run: pwd
      - uses: actions/upload-artifact@v4
        with:
          name: test-file
          path: upload/test.txt

  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: test-file
          path: upload/test.txt
      - run: ls -al
      - run: pwd
